# Generated by Django 4.2.5 on 2023-09-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20230906_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='unitPrice',
            new_name='unit_price',
        ),
    ]
