# Generated by Django 4.2.5 on 2023-09-08 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_unitprice_orderitem_unit_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
    ]
